### ISSUE TITLE
Kavram çevirileri

### ISSUE THREAD

**Issue by RhodosTheGod** [CG-translators/opengl-ogrenin#11]
Temel kavramların çevrilmiş olması anlamayı oldukça güçleştiriyor. Shader, vbo ve vao gibi kavramları metin içerisinde Türkçe kullanıp başta bir yerlerde bir kereye mahsus İngilizcelerini vermektense bir kereye mahsus Türkçeye çevirip metin içerisinde İngilizcelerinin kullanılması takip etmeyi kolaylaştıracaktır. Örneğin: 
![image](https://user-images.githubusercontent.com/61187716/102584449-88cb2500-4117-11eb-9966-193b895b1c78.png)

**Comment by RhodosTheGod** [comment]
"Vertex shader, istediğimiz herhangi bir girdiyi vertex attribute (öznitelik) biçiminde belirtmemize olanak tanır ve bu da esneklik sağlar; vertex shader'a girilen verilerin hangi parçasının vertex attribute'ta nereye geleceğini belirleyebiliriz. Bu, render almadan önce vertex bilgilerinin nasıl yorumlanması gerektiğini belirtmemiz anlamına gelir."

**Comment by NeziheSozen** [comment]
@RhodosTheGod Yorumunuzu henüz gördüm. Dikkate alacağım. Teşekkür ederim.

**Comment by RhodosTheGod** [comment]
Kolayliklar diliyorum, iyi gunler.
