### ISSUE TITLE
Nasil katkida bulunabilirim?

### ISSUE THREAD

**Issue by furkanonder** [CG-translators/opengl-ogrenin#12]
Kitapta bazi yazim hatalari bulunuyor ve bunlari duzeltmek istiyorum. Kitapa dair forklayabilecegim bir repo goremedim. Kitaba nasil katkida bulunabilirim?

**Comment by NeziheSozen** [comment]
Merhaba @furkanonder,

Profilinizdeki mail adresinize kullanıcı adı ve parola bilgisini ilettim. Maalesef gitbook'ta birden fazla kullanıcı alanı açarsak ücrete tabi oluyor bu yüzden tek hesap ve parola ile ilerliyoruz. 

Çevirisini yaptığınız ya da düzeltme yaptığınız sayfaların altına isminizi de lütfen ekleyin. Katkınız için şimdiden teşekkürler.

**Comment by furkanonder** [comment]
@NeziheSozen Rica ederim.
